// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	ciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/cilium.io/v2alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeCiliumTrafficGroups implements CiliumTrafficGroupInterface
type fakeCiliumTrafficGroups struct {
	*gentype.FakeClientWithList[*v2alpha1.CiliumTrafficGroup, *v2alpha1.CiliumTrafficGroupList]
	Fake *FakeCiliumV2alpha1
}

func newFakeCiliumTrafficGroups(fake *FakeCiliumV2alpha1) ciliumiov2alpha1.CiliumTrafficGroupInterface {
	return &fakeCiliumTrafficGroups{
		gentype.NewFakeClientWithList[*v2alpha1.CiliumTrafficGroup, *v2alpha1.CiliumTrafficGroupList](
			fake.Fake,
			"",
			v2alpha1.SchemeGroupVersion.WithResource("ciliumtrafficgroups"),
			v2alpha1.SchemeGroupVersion.WithKind("CiliumTrafficGroup"),
			func() *v2alpha1.CiliumTrafficGroup { return &v2alpha1.CiliumTrafficGroup{} },
			func() *v2alpha1.CiliumTrafficGroupList { return &v2alpha1.CiliumTrafficGroupList{} },
			func(dst, src *v2alpha1.CiliumTrafficGroupList) { dst.ListMeta = src.ListMeta },
			func(list *v2alpha1.CiliumTrafficGroupList) []*v2alpha1.CiliumTrafficGroup {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v2alpha1.CiliumTrafficGroupList, items []*v2alpha1.CiliumTrafficGroup) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
