// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

import (
	context "context"

	ciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CiliumTrafficGroupsGetter has a method to return a CiliumTrafficGroupInterface.
// A group's client should implement this interface.
type CiliumTrafficGroupsGetter interface {
	CiliumTrafficGroups() CiliumTrafficGroupInterface
}

// CiliumTrafficGroupInterface has methods to work with CiliumTrafficGroup resources.
type CiliumTrafficGroupInterface interface {
	Create(ctx context.Context, ciliumTrafficGroup *ciliumiov2alpha1.CiliumTrafficGroup, opts v1.CreateOptions) (*ciliumiov2alpha1.CiliumTrafficGroup, error)
	Update(ctx context.Context, ciliumTrafficGroup *ciliumiov2alpha1.CiliumTrafficGroup, opts v1.UpdateOptions) (*ciliumiov2alpha1.CiliumTrafficGroup, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*ciliumiov2alpha1.CiliumTrafficGroup, error)
	List(ctx context.Context, opts v1.ListOptions) (*ciliumiov2alpha1.CiliumTrafficGroupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *ciliumiov2alpha1.CiliumTrafficGroup, err error)
	CiliumTrafficGroupExpansion
}

// ciliumTrafficGroups implements CiliumTrafficGroupInterface
type ciliumTrafficGroups struct {
	*gentype.ClientWithList[*ciliumiov2alpha1.CiliumTrafficGroup, *ciliumiov2alpha1.CiliumTrafficGroupList]
}

// newCiliumTrafficGroups returns a CiliumTrafficGroups
func newCiliumTrafficGroups(c *CiliumV2alpha1Client) *ciliumTrafficGroups {
	return &ciliumTrafficGroups{
		gentype.NewClientWithList[*ciliumiov2alpha1.CiliumTrafficGroup, *ciliumiov2alpha1.CiliumTrafficGroupList](
			"ciliumtrafficgroups",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *ciliumiov2alpha1.CiliumTrafficGroup { return &ciliumiov2alpha1.CiliumTrafficGroup{} },
			func() *ciliumiov2alpha1.CiliumTrafficGroupList { return &ciliumiov2alpha1.CiliumTrafficGroupList{} },
		),
	}
}
