// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	ciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CiliumTrafficGroupLister helps list CiliumTrafficGroups.
// All objects returned here must be treated as read-only.
type CiliumTrafficGroupLister interface {
	// List lists all CiliumTrafficGroups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ciliumiov2alpha1.CiliumTrafficGroup, err error)
	// Get retrieves the CiliumTrafficGroup from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*ciliumiov2alpha1.CiliumTrafficGroup, error)
	CiliumTrafficGroupListerExpansion
}

// ciliumTrafficGroupLister implements the CiliumTrafficGroupLister interface.
type ciliumTrafficGroupLister struct {
	listers.ResourceIndexer[*ciliumiov2alpha1.CiliumTrafficGroup]
}

// NewCiliumTrafficGroupLister returns a new CiliumTrafficGroupLister.
func NewCiliumTrafficGroupLister(indexer cache.Indexer) CiliumTrafficGroupLister {
	return &ciliumTrafficGroupLister{listers.New[*ciliumiov2alpha1.CiliumTrafficGroup](indexer, ciliumiov2alpha1.Resource("ciliumtrafficgroup"))}
}
